// Learn more about DAX queries at https://aka.ms/dax-queries
// Here is a sample DAX query from your model, click 'Run'
// Try other DAX queries by right clicking a table, column, or measure in the data pane and choosing one from 'Quick queries'
DEFINE
	MEASURE 'Key Measures'[vStartCP] = FIRSTDATE('Date Table'[Date])
	MEASURE 'Key Measures'[vEndCP] = LASTDATE('Date Table'[Date])
	MEASURE 'Key Measures'[vDaysInPeriod] = DATEDIFF(
		[vStartCP],
		[vEndCP],
		DAY
	)
	MEASURE 'Key Measures'[vStartPP] = PREVIOUSDAY(FIRSTDATE(DATEADD(
				'Date Table'[Date],
				-1 * [vDaysInPeriod],
				DAY
			)))
	MEASURE 'Key Measures'[vEndPP] = PREVIOUSDAY(LASTDATE(DATEADD(
				'Date Table'[Date],
				-1 * [vDaysInPeriod],
				DAY
			)))

EVALUATE
	CALCULATETABLE(
		DATESBETWEEN(
			'Date Table'[Date],
			[vStartPP],
			[vEndPP]
		),
		FILTER(
			ALL('Date Table'),
			'Date Table'[Date] >= DATE(2024, 01, 01) && 'Date Table'[Date] <= DATE(2024, 03, 31)
		)
	)