EVALUATE
FILTER(
SUMMARIZE(
	'Involved Person',
	Contact[PK_contactid],
	"Suburbs", CALCULATE(
    FIRSTNONBLANK('Linked Address'[Suburbs], 1),
    FILTER(ALL('Linked Address'), 'Linked Address'[FK_hs_person] = Contact[PK_contactid] && ('Linked Address'[Is Location] = "Yes" && 'Linked Address'[Primary] = "Yes") && 'Linked Address'[Status] = "Active")
)), NOT ISBLANK([Suburbs])
)
