EVALUATE
	ADDCOLUMNS(
		SUMMARIZE(
			'Involved Person',
			'CSRI Intake'[PK_hs_csri_intakeid],
			'CSRI Intake'[Created On],
			'Contact'[Unborn Child],
			'Contact'[Birth Date]
		),
		"Age Group", VAR vYear = INT(DIVIDE(
				DATEDIFF(
					'Contact'[Birth Date],
					'CSRI Intake'[Created On],
					DAY
				),
				365.25,
				0
			))
		RETURN
			SWITCH(
				TRUE(),
				'Contact'[Unborn Child] = "Yes", "Unborn",
				OR(
					vYear < 0,
					ISBLANK(vYear)
				), "Unknown",
				vYear < 4, "Under 4",
				vYear < 10, "4 to Under 10",
				vYear < 15, "10 to Under 15",
				vYear > 15, "15+",
				"Unknown"
			)
	)
	ORDER BY 'CSRI Intake'[PK_hs_csri_intakeid]